version: '3.8'

services:
  claw_redis:
    image: redis:alpine
    container_name: claw_redis
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./redis.conf
        target: /redis.conf
      - claw_redis_data:/data
    command: redis-server /redis.conf
    restart: unless-stopped
  

volumes:
  claw_redis_data: