app = 'data-storage'
primary_region = "sin"

[build]
  image = 'influxdb:2.7-alpine'

[env]
  INFLUXDB_HTTP_BIND_ADDRESS = "0.0.0.0:8086"

[[mounts]]
  source = 'influxdb_data'
  destination = '/var/lib/influxdb2'

[[services]]
  protocol = 'tcp'
  internal_port = 8086

  [[services.ports]]
    port = 8086
    handlers = ['http']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1